# Generated by Django 5.1.4 on 2024-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_by_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите название книги')),
                ('price', models.FloatField(default=100, verbose_name='Задайте цену книги')),
                ('tags', models.ManyToManyField(to='books_by_categories.tag')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
