# Generated by Django 5.1.4 on 2024-12-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_blog', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.TextField(default='@Diligens_Deum')),
                ('phone_number', models.CharField(choices=[('✅', '✅'), ('❌', '❌')], max_length=15)),
                ('book_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_book', to='library_blog.bookmodel')),
            ],
        ),
    ]
