# Generated by Django 5.1.4 on 2024-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketmodel',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.RenameField(
            model_name='basketmodel',
            old_name='book_by',
            new_name='book_buy',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='book',
            field=models.URLField(null=True, verbose_name='Укажите ссылку аудио книги'),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Введите имя'),
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Укажите эл.почту '),
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Введите номер телефона'),
        ),
    ]
